Configuration:
  status: warn
  Appenders:
    Console:
      name: CONSOLE
      target: SYSTEM_OUT
      PatternLayout:
        pattern: '%d{yyyy-MM-dd HH:mm:ss,SSS} %-5level %c{1}.%M(%L) - %msg%n'
    RollingRandomAccessFile:
      - name: INFO
        fileName: log/capstone-project.log
        filePattern: log/$${date:yyyy-MM}/%d{yyyy-MM-dd}-product-policy-%i.log.gz
        PatternLayout:
          pattern: '%d{yyyy-MM-dd HH:mm:ss,SSS} %-5level %c{1}.%M(%L) - %msg%n'
        Policies:
          TimeBasedTriggeringPolicy: {
          }
          OnStartupTriggeringPolicy: {
          }
          SizeBasedTriggeringPolicy:
            size: 200 MB
        DefaultRollOverStrategy:
          max: 20
      - name: ERROR
        fileName: log/capstone-project-error.log
        filePattern: log/$${date:yyyy-MM}/%d{yyyy-MM-dd}-product-policy-error-%i.log.gz
        PatternLayout:
          pattern: '%d{yyyy-MM-dd HH:mm:ss,SSS} %-5level %c{1}.%M(%L) - %msg%n'
        Policies:
          TimeBasedTriggeringPolicy: {
          }
          OnStartupTriggeringPolicy: {
          }
          SizeBasedTriggeringPolicy:
            size: 200 MB
        DefaultRollOverStrategy:
          max: 10
  Loggers:
    Logger:
      - name: EventLogger
        level: info
        additivity: false
        AppenderRef:
          - ref: ERROR
          - ref: INFO
    Root:
      level: info
      AppenderRef:
        - ref: CONSOLE
        - ref: ERROR
          level: error
        - ref: INFO